config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :shipping_methods
  resources :payments
  resources :payment_methods
  resources :product_taxons
  resources :taxons
  resources :taxonomies
  resources :shipping_categories
  resources :tax_rates
  resources :product_properties
  resources :properties
  resources :product_option_types
  resources :varients
  resources :option_types
  resources :tax_categories
  resources :products
  resources :countries
  resources :states
  resources :zones
  resources :promotion_categories
  resources :promotions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many:state
end

app/models/option_type.rb
class OptionType < ApplicationRecord
	has_many:product_option_types
	has_many:products, through: :product_option_types
	


end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
	belongs_to:store
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:product_option_types
	has_many:option_types, through: :product_option_types
	has_many:product_properties
	has_many:properties, through: :product_properties
	belongs_to:tax_category
	has_many:varients
	belongs_to:shipping_category
	has_many:product_taxons
	has_many:taxons, through: :product_taxons
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
	belongs_to:taxon
	belongs_to:product
end

app/models/promotion.rb
class Promotion < ApplicationRecord
	belongs_to:promotion_category
end

app/models/property.rb
class Property < ApplicationRecord
	has_many:product_properties
	has_many:products, through: :product_properties
end

app/models/state.rb
class State < ApplicationRecord
	has_many:zones
	belongs_to:country
end

app/models/store.rb
class Store < ApplicationRecord
	has_many:payment_methods
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
	has_many:products
	has_many:tax_rates
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
	belongs_to:zone
	belongs_to:tax_category
end

app/models/taxon.rb
class Taxon < ApplicationRecord
	belongs_to:taxonomy
	has_many:product_taxons
	has_many:products, through: :product_taxons
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
	has_many:taxons
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/varient.rb
class Varient < ApplicationRecord
	belongs_to:product
end

app/models/zone.rb
class Zone < ApplicationRecord
	belongs_to:state
	has_many:tax_rates
	belongs_to:shipping_method
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :url, :seo_title, :meta_discription, :meta_keyword, :currency)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/taxons_helper.rb
module TaxonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :seo_title %>
    <%= form.text_field :seo_title %>
  </div>

  <div class="field">
    <%= form.label :meta_discription %>
    <%= form.text_field :meta_discription %>
  </div>

  <div class="field">
    <%= form.label :meta_keyword %>
    <%= form.text_field :meta_keyword %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Seo title</th>
      <th>Meta discription</th>
      <th>Meta keyword</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.url %></td>
        <td><%= store.seo_title %></td>
        <td><%= store.meta_discription %></td>
        <td><%= store.meta_keyword %></td>
        <td><%= store.currency %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @store.url %>
</p>

<p>
  <strong>Seo title:</strong>
  <%= @store.seo_title %>
</p>

<p>
  <strong>Meta discription:</strong>
  <%= @store.meta_discription %>
</p>

<p>
  <strong>Meta keyword:</strong>
  <%= @store.meta_keyword %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @store.currency %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>