config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :shipping_methods
  resources :payments
  resources :payment_methods
  resources :product_taxons
  resources :taxons
  resources :taxonomies
  resources :shipping_categories
  resources :tax_rates
  resources :product_properties
  resources :properties
  resources :product_option_types
  resources :varients
  resources :option_types
  resources :tax_categories
  resources :products
  resources :countries
  resources :states
  resources :zones
  resources :promotion_categories
  resources :promotions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many:state
end

app/models/option_type.rb
class OptionType < ApplicationRecord
	has_many:product_option_types
	has_many:products, through: :product_option_types
	


end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:product_option_types
	has_many:option_types, through: :product_option_types
	has_many:product_properties
	has_many:properties, through: :product_properties
	belongs_to:tax_category
	has_many:varients
	belongs_to:shipping_category
	has_many:product_taxons
	has_many:taxons, through: :product_taxons
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
	belongs_to:taxon
	belongs_to:product
end

app/models/promotion.rb
class Promotion < ApplicationRecord
	belongs_to:promotion_category
end

app/models/property.rb
class Property < ApplicationRecord
	has_many:product_properties
	has_many:products, through: :product_properties
end

app/models/shipping_method.rb
class ShippingMethod < ApplicationRecord
	has_many:zones
end

app/models/state.rb
class State < ApplicationRecord
	has_many:zones
	belongs_to:country
end

app/models/store.rb
class Store < ApplicationRecord
	has_many:payment_methods
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
	has_many:products
	has_many:tax_rates
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
	belongs_to:zone
	belongs_to:tax_category
end

app/models/taxon.rb
class Taxon < ApplicationRecord
	belongs_to:taxonomy
	has_many:product_taxons
	has_many:products, through: :product_taxons
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
	has_many:taxons
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/varient.rb
class Varient < ApplicationRecord
	belongs_to:product
end

app/models/zone.rb
class Zone < ApplicationRecord
	belongs_to:state
	has_many:tax_rates
	belongs_to:shipping_method
end

app/controllers/shipping_methods_controller.rb
class ShippingMethodsController < ApplicationController
  before_action :set_shipping_method, only: %i[ show edit update destroy ]

  # GET /shipping_methods or /shipping_methods.json
  def index
    @shipping_methods = ShippingMethod.all
  end

  # GET /shipping_methods/1 or /shipping_methods/1.json
  def show
  end

  # GET /shipping_methods/new
  def new
    @shipping_method = ShippingMethod.new
  end

  # GET /shipping_methods/1/edit
  def edit
  end

  # POST /shipping_methods or /shipping_methods.json
  def create
    @shipping_method = ShippingMethod.new(shipping_method_params)

    respond_to do |format|
      if @shipping_method.save
        format.html { redirect_to @shipping_method, notice: "Shipping method was successfully created." }
        format.json { render :show, status: :created, location: @shipping_method }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipping_methods/1 or /shipping_methods/1.json
  def update
    respond_to do |format|
      if @shipping_method.update(shipping_method_params)
        format.html { redirect_to @shipping_method, notice: "Shipping method was successfully updated." }
        format.json { render :show, status: :ok, location: @shipping_method }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_methods/1 or /shipping_methods/1.json
  def destroy
    @shipping_method.destroy
    respond_to do |format|
      format.html { redirect_to shipping_methods_url, notice: "Shipping method was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping_method
      @shipping_method = ShippingMethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shipping_method_params
      params.require(:shipping_method).permit(:name, :zone_id, :shipping_category_id, :tax_category_id)
    end
end

app/helpers/shipping_methods_helper.rb
module ShippingMethodsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/shipping_methods/_form.html.erb
<%= form_with(model: shipping_method) do |form| %>
  <% if shipping_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipping_method.errors.count, "error") %> prohibited this shipping_method from being saved:</h2>

      <ul>
        <% shipping_method.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :zone_id %>
    <%= form.number_field :zone_id %>
  </div>

  <div class="field">
    <%= form.label :shipping_category_id %>
    <%= form.number_field :shipping_category_id %>
  </div>

  <div class="field">
    <%= form.label :tax_category_id %>
    <%= form.number_field :tax_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shipping_methods/edit.html.erb
<h1>Editing Shipping Method</h1>

<%= render 'form', shipping_method: @shipping_method %>

<%= link_to 'Show', @shipping_method %> |
<%= link_to 'Back', shipping_methods_path %>

app/views/shipping_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipping Methods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Zone</th>
      <th>Shipping category</th>
      <th>Tax category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipping_methods.each do |shipping_method| %>
      <tr>
        <td><%= shipping_method.name %></td>
        <td><%= shipping_method.zone_id %></td>
        <td><%= shipping_method.shipping_category_id %></td>
        <td><%= shipping_method.tax_category_id %></td>
        <td><%= link_to 'Show', shipping_method %></td>
        <td><%= link_to 'Edit', edit_shipping_method_path(shipping_method) %></td>
        <td><%= link_to 'Destroy', shipping_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping Method', new_shipping_method_path %>

app/views/shipping_methods/new.html.erb
<h1>New Shipping Method</h1>

<%= render 'form', shipping_method: @shipping_method %>

<%= link_to 'Back', shipping_methods_path %>

app/views/shipping_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shipping_method.name %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @shipping_method.zone_id %>
</p>

<p>
  <strong>Shipping category:</strong>
  <%= @shipping_method.shipping_category_id %>
</p>

<p>
  <strong>Tax category:</strong>
  <%= @shipping_method.tax_category_id %>
</p>

<%= link_to 'Edit', edit_shipping_method_path(@shipping_method) %> |
<%= link_to 'Back', shipping_methods_path %>