config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :shipping_methods
  resources :payments
  resources :payment_methods
  resources :product_taxons
  resources :taxons
  resources :taxonomies
  resources :shipping_categories
  resources :tax_rates
  resources :product_properties
  resources :properties
  resources :product_option_types
  resources :varients
  resources :option_types
  resources :tax_categories
  resources :products
  resources :countries
  resources :states
  resources :zones
  resources :promotion_categories
  resources :promotions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many:state
end

app/models/option_type.rb
class OptionType < ApplicationRecord
	has_many:product_option_types
	has_many:products, through: :product_option_types
	


end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:product_option_types
	has_many:option_types, through: :product_option_types
	has_many:product_properties
	has_many:properties, through: :product_properties
	belongs_to:tax_category
	has_many:varients
	belongs_to:shipping_category
	has_many:product_taxons
	has_many:taxons, through: :product_taxons
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
	belongs_to:taxon
	belongs_to:product
end

app/models/promotion.rb
class Promotion < ApplicationRecord
	belongs_to:promotion_category
end

app/models/property.rb
class Property < ApplicationRecord
	has_many:product_properties
	has_many:products, through: :product_properties
end

app/models/state.rb
class State < ApplicationRecord
	has_many:zones
	belongs_to:country
end

app/models/store.rb
class Store < ApplicationRecord
	has_many:payment_methods
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
	has_many:products
	has_many:tax_rates
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
	belongs_to:zone
	belongs_to:tax_category
end

app/models/taxon.rb
class Taxon < ApplicationRecord
	belongs_to:taxonomy
	has_many:product_taxons
	has_many:products, through: :product_taxons
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
	has_many:taxons
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/varient.rb
class Varient < ApplicationRecord
	belongs_to:product
end

app/models/zone.rb
class Zone < ApplicationRecord
	belongs_to:state
	has_many:tax_rates
	belongs_to:shipping_method
end

app/controllers/tax_categories_controller.rb
class TaxCategoriesController < ApplicationController
  before_action :set_tax_category, only: %i[ show edit update destroy ]

  # GET /tax_categories or /tax_categories.json
  def index
    @tax_categories = TaxCategory.all
  end

  # GET /tax_categories/1 or /tax_categories/1.json
  def show
  end

  # GET /tax_categories/new
  def new
    @tax_category = TaxCategory.new
  end

  # GET /tax_categories/1/edit
  def edit
  end

  # POST /tax_categories or /tax_categories.json
  def create
    @tax_category = TaxCategory.new(tax_category_params)

    respond_to do |format|
      if @tax_category.save
        format.html { redirect_to @tax_category, notice: "Tax category was successfully created." }
        format.json { render :show, status: :created, location: @tax_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tax_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tax_categories/1 or /tax_categories/1.json
  def update
    respond_to do |format|
      if @tax_category.update(tax_category_params)
        format.html { redirect_to @tax_category, notice: "Tax category was successfully updated." }
        format.json { render :show, status: :ok, location: @tax_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tax_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tax_categories/1 or /tax_categories/1.json
  def destroy
    @tax_category.destroy
    respond_to do |format|
      format.html { redirect_to tax_categories_url, notice: "Tax category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tax_category
      @tax_category = TaxCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tax_category_params
      params.require(:tax_category).permit(:name, :discription, :code)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/tax_categories_helper.rb
module TaxCategoriesHelper
end

app/helpers/taxons_helper.rb
module TaxonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/tax_categories/_form.html.erb
<%= form_with(model: tax_category) do |form| %>
  <% if tax_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tax_category.errors.count, "error") %> prohibited this tax_category from being saved:</h2>

      <ul>
        <% tax_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_field :discription %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tax_categories/edit.html.erb
<h1>Editing Tax Category</h1>

<%= render 'form', tax_category: @tax_category %>

<%= link_to 'Show', @tax_category %> |
<%= link_to 'Back', tax_categories_path %>

app/views/tax_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tax Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Discription</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tax_categories.each do |tax_category| %>
      <tr>
        <td><%= tax_category.name %></td>
        <td><%= tax_category.discription %></td>
        <td><%= tax_category.code %></td>
        <td><%= link_to 'Show', tax_category %></td>
        <td><%= link_to 'Edit', edit_tax_category_path(tax_category) %></td>
        <td><%= link_to 'Destroy', tax_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tax Category', new_tax_category_path %>

app/views/tax_categories/new.html.erb
<h1>New Tax Category</h1>

<%= render 'form', tax_category: @tax_category %>

<%= link_to 'Back', tax_categories_path %>

app/views/tax_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tax_category.name %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @tax_category.discription %>
</p>

<p>
  <strong>Code:</strong>
  <%= @tax_category.code %>
</p>

<%= link_to 'Edit', edit_tax_category_path(@tax_category) %> |
<%= link_to 'Back', tax_categories_path %>