config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :shipping_methods
  resources :payments
  resources :payment_methods
  resources :product_taxons
  resources :taxons
  resources :taxonomies
  resources :shipping_categories
  resources :tax_rates
  resources :product_properties
  resources :properties
  resources :product_option_types
  resources :varients
  resources :option_types
  resources :tax_categories
  resources :products
  resources :countries
  resources :states
  resources :zones
  resources :promotion_categories
  resources :promotions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many:state
end

app/models/option_type.rb
class OptionType < ApplicationRecord
	has_many:product_option_types
	has_many:products, through: :product_option_types
	


end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many:product_option_types
	has_many:option_types, through: :product_option_types
	has_many:product_properties
	has_many:properties, through: :product_properties
	belongs_to:tax_category
	has_many:varients
	belongs_to:shipping_category
	has_many:product_taxons
	has_many:taxons, through: :product_taxons
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
	belongs_to:taxon
	belongs_to:product
end

app/models/promotion.rb
class Promotion < ApplicationRecord
	belongs_to:promotion_category
end

app/models/property.rb
class Property < ApplicationRecord
	has_many:product_properties
	has_many:products, through: :product_properties
end

app/models/state.rb
class State < ApplicationRecord
	has_many:zones
	belongs_to:country
end

app/models/store.rb
class Store < ApplicationRecord
	has_many:payment_methods
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
	has_many:products
	has_many:tax_rates
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
	belongs_to:zone
	belongs_to:tax_category
end

app/models/taxon.rb
class Taxon < ApplicationRecord
	belongs_to:taxonomy
	has_many:product_taxons
	has_many:products, through: :product_taxons
end

app/models/taxonomy.rb
class Taxonomy < ApplicationRecord
	has_many:taxons
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/varient.rb
class Varient < ApplicationRecord
	belongs_to:product
end

app/models/zone.rb
class Zone < ApplicationRecord
	belongs_to:state
	has_many:tax_rates
	belongs_to:shipping_method
end

app/controllers/product_option_types_controller.rb
class ProductOptionTypesController < ApplicationController
  before_action :set_product_option_type, only: %i[ show edit update destroy ]

  # GET /product_option_types or /product_option_types.json
  def index
    @product_option_types = ProductOptionType.all
  end

  # GET /product_option_types/1 or /product_option_types/1.json
  def show
  end

  # GET /product_option_types/new
  def new
    @product_option_type = ProductOptionType.new
  end

  # GET /product_option_types/1/edit
  def edit
  end

  # POST /product_option_types or /product_option_types.json
  def create
    @product_option_type = ProductOptionType.new(product_option_type_params)

    respond_to do |format|
      if @product_option_type.save
        format.html { redirect_to @product_option_type, notice: "Product option type was successfully created." }
        format.json { render :show, status: :created, location: @product_option_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_option_types/1 or /product_option_types/1.json
  def update
    respond_to do |format|
      if @product_option_type.update(product_option_type_params)
        format.html { redirect_to @product_option_type, notice: "Product option type was successfully updated." }
        format.json { render :show, status: :ok, location: @product_option_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_option_types/1 or /product_option_types/1.json
  def destroy
    @product_option_type.destroy
    respond_to do |format|
      format.html { redirect_to product_option_types_url, notice: "Product option type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_option_type
      @product_option_type = ProductOptionType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_option_type_params
      params.require(:product_option_type).permit(:option_type_id, :product)
    end
end

app/helpers/product_option_types_helper.rb
module ProductOptionTypesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/product_option_types/_form.html.erb
<%= form_with(model: product_option_type) do |form| %>
  <% if product_option_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_option_type.errors.count, "error") %> prohibited this product_option_type from being saved:</h2>

      <ul>
        <% product_option_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :option_type_id %>
    <%= form.number_field :option_type_id %>
  </div>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_option_types/edit.html.erb
<h1>Editing Product Option Type</h1>

<%= render 'form', product_option_type: @product_option_type %>

<%= link_to 'Show', @product_option_type %> |
<%= link_to 'Back', product_option_types_path %>

app/views/product_option_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Option Types</h1>

<table>
  <thead>
    <tr>
      <th>Option type</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_option_types.each do |product_option_type| %>
      <tr>
        <td><%= product_option_type.option_type_id %></td>
        <td><%= product_option_type.product %></td>
        <td><%= link_to 'Show', product_option_type %></td>
        <td><%= link_to 'Edit', edit_product_option_type_path(product_option_type) %></td>
        <td><%= link_to 'Destroy', product_option_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Option Type', new_product_option_type_path %>

app/views/product_option_types/new.html.erb
<h1>New Product Option Type</h1>

<%= render 'form', product_option_type: @product_option_type %>

<%= link_to 'Back', product_option_types_path %>

app/views/product_option_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Option type:</strong>
  <%= @product_option_type.option_type_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_option_type.product %>
</p>

<%= link_to 'Edit', edit_product_option_type_path(@product_option_type) %> |
<%= link_to 'Back', product_option_types_path %>